Update nginx_install

diff --git a/nginx_install b/nginx_install
--- a/nginx_install
+++ b/nginx_install
@@ -1,46 +1,120 @@
 #!/bin/bash
 
+#exit option
 set -e
 
 
 
 #check if su
 
-#if [[ $EUID -ne 0 ]]; then
- #   echo "Please use the script with superuser"
-  #  exit 
-#fi
-#DISTRO_NAME="$(lsb_release -si)";
+if [[ $EUID -ne 0 ]]; then
+   echo -e "Please use the script with superuser"
+   exit 
+fi
+
+#gets the OS information as variable
 source /etc/os-release
 DISTRO_NAME_HUMAN="$(gawk -F'"' '{print $2}' /etc/os-release | head -1)"
-#echo $DISTRO_NAME
-#echo $ID
 
-function if_ubuntu () {
-if [[ "$VERSION_ID" != "18.04" ]]; then
-    echo Version of the $DISTRO_NAME_HUMAN should be 18.04!
-    exit 1
-fi
+
+
+#Version check for ubuntu and centos
+    function if_ubuntu () {
+        WHICH_OS=ubuntuu
+        if [[ "$VERSION_ID" != "18.04" ]]; then
+            echo -e "Version of the $DISTRO_NAME_HUMAN should be 18.04!"
+             exit 1
+        else 
+            echo -e "Starting installation for $PRETTY_NAME!"
+        fi
+        }
+#Check version of the CentOS
+    function if_centos () {
+        WHICH_OS=centoss
+        if [ "$VERSION_ID" != "7"]; then
+            echo -e "Version of the $DISTRO_NAME_HUMAN should be 7!"
+            exit 1
+        else
+            echo -e "Starting installation for $PRETTY_NAME!"
+        fi
+}
+#Cheks is nginx installed
+    function install_nginx_u () {
+
+        if [ ! -w /etc/nginx/sites-available/default ]; then
+            echo -e "Installing Nginx"
+            apt install nginx -y
+        fi
+#if nginx is already installed changes listen port to 80 at default .conf
+        if [ -w /etc/nginx/sites-available/default ]; then
+            echo -e "Nginx is installed."
+           sed -i 's/listen 80/listen 8000/' /etc/nginx/sites-available/default
+           sed -i 's/:]:80/:]:8000/' /etc/nginx/sites-available/default
+            echo -e "Changing listening port from 80 to 8000"
+        fi
+}
+#if nginx is already installed changes listen port to 80 at default .conf
+    function install_nginx_c () {
+        if [ ! -w /etc/nginx/nginx.conf ]; then
+            echo -e "Installing Nginx"
+            yum -y install nginx
+        fi
+
+        if [ -w /etc/nginx/nginx.conf ]; then
+        echo -e "Nginx is installed, continuing."
+           sed -i 's/listen 80/listen 8000/' /etc/nginx/nginx.conf
+           sed -i 's/:]:80/:]:8000/' /etc/nginx/nginx.conf
+         echo -e "Changing listening port from 80 to 8000"
+        fi
+}
+#Ask for system update
+function ubuntu_sysupdate(){
+    while true; do
+    read -p "Do you wish to update your Os?: " yn
+    case $yn in
+        [Yy]* ) apt-get update; break;;
+        [Nn]* ) break;;
+        * ) echo -e "Please answer yes or no.";;
+    esac
+done
+}
+function centos_sysupdate(){
+        while true; do
+    read -p "Do you wish to update the Os?: " yn
+    case $yn in
+        [Yy]* ) yum update; break;;
+        [Nn]* ) break;;
+        * ) echo -e "Please answer yes or no.";;
+    esac
+done
 }
 
-function if_centos ()
-{
-        if [ "$VERSION_ID" != "7"]; then
-            echo "Version of the $DISTRO_NAME_HUMAN should be 7!"
+#gets the default directory for the index.html file
+#Cleans and creates example html file at main folder
+function default_html(){
+     ROOT_DIR=$(grep root -m1 /etc/nginx/sites-available/default | cut -d " " -f2 | sed 's/;$//')
+   find $ROOT_DIR -type f -delete
+   echo "<html><body><h1>Testing one two tree</h1><img src="https://scontent.fadb6-5.fna.fbcdn.net/v/t31.18172-8/10608762_10204531125785467_1512482668131383046_o.jpg?_nc_cat=105&ccb=1-5&_nc_sid=174925&_nc_ohc=NoWp4GFHYHgAX9xIW5Y&_nc_ht=scontent.fadb6-5.fna&oh=00_AT--yVftjVo5EF1inzITPEQ3_Npe6kMnHTOXjfhhuQIH1w&oe=61FC7DF4" alt="kurcalamaaa"></body></html>" >$ROOT_DIR/index.html
+}
+#Checks which OS is running
+if [ "$ID" == "ubuntu" ]; then
+        ubuntu_sysupdate
+        if_ubuntu
+    elif [ "$ID" == "centos" ]; then
+         centos_sysupdate
+         if_centos
+else
+    echo -e "Operating system should be Ubuntu 18.04 or CentOs 7 $PRETTY_NAME is not supported."
+    exit 1
+fi
+if [ "$WHICH_OS" == "ubuntuu" ]; then
+        install_nginx_u
+    elif [ "$WHICH_OS" == "centoss" ]; then
+        install_nginx_c
+    else
+        echo -e "An error occured cannot verify the type of the Operating system."
             exit 1
 fi
-}
-if [ "$ID" == "ubuntu" ] || [ "$ID" == "centos" ]; then
-    if_ubuntu
-elif [ "$ID" == "centos" ]; then
-    if_centos
-else
-    echo "Operating system should be Ubuntu 18.04 or CentOs 7"
-    exit 1
-fi
-
-
-
-#lsb_release -sr | cut -d '.' -f 1
-
-#    echo "Starting installation for $DISTRO_NAME_HUMAN"
+default_html
+echo "Installation successfull. Creating default page."
+service nginx restart
